Bài 1

In [4]:
#tao bang
import numpy as np
from math import acos, degrees

A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])
#Bai 1.a
sum_AB = A + B
tich = 3 * A - 2 * B
print("a)")
print("Tổng A + B:", sum_AB)
print("Tích 3A - 2B:", tich)

#Bai 1.b
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_deg = degrees(acos(cos_theta))
print("\nb)")
print("Tích vô hướng A · B:", dot_product)
print("Góc giữa A và B (độ):", round(angle_deg, 3))

# Bai 1.c
Ct = C.T
CtC = Ct @ C
print("\nc)")
print("Tích C^T * C:\n", CtC)


a)
Tổng A + B: [3 3 1 5]
Tích 3A - 2B: [  4 -11  13 -10]

b)
Tích vô hướng A · B: -8
Góc giữa A và B (độ): 108.376

c)
Tích C^T * C:
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


Bai 2

In [5]:
import numpy as np
# Ma trận M và N
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])
N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])
#a
product = np.dot(M, N)
print("cau a: M × N =")
print(product)
#b
try:
    det_M = np.linalg.det(M)
    print("\n cau b:  Định thức của M =", det_M)
except np.linalg.LinAlgError:
    print("\n cau b: Không thể tính định thức của M vì M không phải là ma trận vuông.")
#c
rank_N = np.linalg.matrix_rank(N)
print("\n cau c: Hạng của ma trận N =", rank_N)

cau a: M × N =
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

 cau b:  Định thức của M = 6.66133814775094e-16

 cau c: Hạng của ma trận N = 2


Bai 3

In [6]:
#Bài 3
import numpy as np
P = np.array([
    [2, 1, 0, -1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])
b = np.array([4, 7, 9, 5])

# a) Tính ma trận nghịch đảo của P (nếu có)
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo P⁻¹:\n", np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (det(P) = 0)")

# b) Giải hệ phương trình x = P⁻¹ * b
try:
    x = np.linalg.solve(P, b)
    print("\nb) Nghiệm của hệ phương trình:\n", np.round(x, 3))
except np.linalg.LinAlgError:
    print("\nb) Không thể giải hệ phương trình vì P không khả nghịch")

# c) Kiểm tra lại bằng cách nhân P * x = b?
if 'x' in locals():
    check = np.dot(P, x)
    print("\nc) Kiểm tra lại P * x:\n", np.round(check, 3))
    print("   So sánh với b:", b)

a) Ma trận nghịch đảo P⁻¹:
 [[ 0.477 -0.182  0.045  0.068]
 [ 0.034  0.273 -0.068  0.148]
 [-0.114  0.091  0.227 -0.159]
 [-0.011 -0.091  0.023  0.284]]

b) Nghiệm của hệ phương trình:
 [1.386 2.17  1.432 0.943]

c) Kiểm tra lại P * x:
 [4. 7. 9. 5.]
   So sánh với b: [4 7 9 5]


Bai 4

In [7]:
#Bai 4
import numpy as np
Q = np.array([
    [4, -1, 0],
    [1, 3, -2],
    [0, 1, 2]
])
eigenvalues, eigenvectors = np.linalg.eig(Q)
#a
print("a) Các giá trị riêng của Q:")
print(np.round(eigenvalues, 3))
#b
print("\nb) Các vector riêng (cột là vector riêng tương ứng):")
print(np.round(eigenvectors, 3))
#c
norm_vectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("\nc) Vector riêng sau chuẩn hóa (độ dài = 1):")
print(np.round(norm_vectors, 3))

a) Các giá trị riêng của Q:
[3.453+0.j    2.773+1.468j 2.773-1.468j]

b) Các vector riêng (cột là vector riêng tương ứng):
[[ 0.833+0.j    -0.262-0.314j -0.262+0.314j]
 [ 0.455+0.j    -0.782+0.j    -0.782-0.j   ]
 [ 0.313+0.j    -0.22 +0.417j -0.22 -0.417j]]

c) Vector riêng sau chuẩn hóa (độ dài = 1):
[[ 0.833+0.j    -0.262-0.314j -0.262+0.314j]
 [ 0.455+0.j    -0.782+0.j    -0.782+0.j   ]
 [ 0.313+0.j    -0.22 +0.417j -0.22 -0.417j]]


Bai 5

In [8]:
#Bai 5
import numpy as np

# Tao ma tran
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])
b = np.array([10, 8, 7])
#a
x_solve = np.linalg.solve(R, b)
print("a) Nghiệm x của hệ phương trình Rx = b:")
print(np.round(x_solve, 3))
#b
det_R = np.linalg.det(R)
if det_R != 0:
    R_inv = np.linalg.inv(R)
    x_inv = R_inv @ b
    print("\nb) Ma trận R khả nghịch (det(R) = {:.3f})".format(det_R))
    print("   Nghiệm x tính bằng R⁻¹ * b:")
    print(np.round(x_inv, 3))
    print("   So sánh với np.linalg.solve():", np.allclose(x_solve, x_inv))
else:
    print("\nb) Ma trận R không khả nghịch (det = 0) ⇒ không thể tính R⁻¹.")
#c
frobenius_norm = np.linalg.norm(R, ord='fro')
print("\nc) Chuẩn Frobenius của ma trận R: {:.3f}".format(frobenius_norm))

a) Nghiệm x của hệ phương trình Rx = b:
[2.783 0.043 2.435]

b) Ma trận R khả nghịch (det(R) = 23.000)
   Nghiệm x tính bằng R⁻¹ * b:
[2.783 0.043 2.435]
   So sánh với np.linalg.solve(): True

c) Chuẩn Frobenius của ma trận R: 6.083
