Bài 1

In [2]:
import numpy as np

# Vector A và B
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])

# a) Tổng và tích tuyến tính
sum_AB = A + B
linear_combination = 2 * A + 3 * B

print("a) A + B =", sum_AB)
print("2A + 3B =", linear_combination)

# b) Tích vô hướng và góc giữa 2 vector
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_degree = np.degrees(np.arccos(cos_theta))

print("b) A · B =", dot_product)
print("Góc giữa A và B =", round(angle_degree, 3), "độ")

# c) Ma trận C nhân với C chuyển vị
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])

C_CT = C @ C.T
print("c) C * C^T =\n", C_CT)


a) A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]
b) A · B = -5
Góc giữa A và B = 99.594 độ
c) C * C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


Bài 2

In [3]:
# Ma trận M và N
M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]])

N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]])

# a) Tích M × N
product_MN = M @ N
print("a) M × N =\n", product_MN)

# b) Định thức của M
det_M = np.linalg.det(M)
print("b) Định thức M =", det_M)

# c) Hạng của N
rank_N = np.linalg.matrix_rank(N)
print("c) Hạng của N =", rank_N)


a) M × N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
b) Định thức M = 409.00000000000017
c) Hạng của N = 4


Bài 3

In [4]:
# Ma trận P
P = np.array([[3, -1, 0, 2],
              [1, 4, -2, 0],
              [0, 1, 5, -1],
              [2, 0, 1, 3]])

# Vector hằng số
b = np.array([6, 8, 3, 7])

# a) Ma trận nghịch đảo
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo P^-1 =\n", P_inv)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch")

# b) Giải hệ bằng nghịch đảo
x = P_inv @ b
print("b) Nghiệm x =", x)

# c) Kiểm tra lại nghiệm
check = P @ x
print("c) Kiểm tra P @ x =", check)
print("So sánh với b =", b)


a) Ma trận nghịch đảo P^-1 =
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
b) Nghiệm x = [2.         1.71428571 0.42857143 0.85714286]
c) Kiểm tra P @ x = [6. 8. 3. 7.]
So sánh với b = [6 8 3 7]


Bài 4

In [5]:
# Ma trận Q
Q = np.array([[5, -2, 1],
              [0, 3, -1],
              [2, 0, 4]])

# a) Giá trị riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("a) Giá trị riêng =", eigenvalues)

# b) Vector riêng
print("b) Vector riêng (theo cột):\n", eigenvectors)

# c) Chuẩn hóa vector riêng
norm_vectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)
print("c) Vector riêng đã chuẩn hóa:\n", norm_vectors)


a) Giá trị riêng = [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]
b) Vector riêng (theo cột):
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]
c) Vector riêng đã chuẩn hóa:
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]


Bài 5

In [ ]:
# Ma trận R và vector b
R = np.array([[4, -1, 2],
              [1, 3, -2],
              [0, 2, 5]])

b = np.array([12, 5, 9])

# a) Giải hệ phương trình
x = np.linalg.solve(R, b)
print("a) Nghiệm x =", x)

# b) Nghịch đảo R và so sánh nghiệm
try:
    R_inv = np.linalg.inv(R)
    x_check = R_inv @ b
    print("b) R^-1 =\n", R_inv)
    print("Nghiệm tính bằng R^-1 * b =", x_check)
    print("So sánh 2 nghiệm:", np.allclose(x, x_check))
except np.linalg.LinAlgError:
    print("R không khả nghịch")

# c) Chuẩn Frobenius
fro_norm = np.linalg.norm(R, 'fro')
print("c) Chuẩn Frobenius của R =", fro_norm)
