#bài thực hành

In [9]:
#thực hành 1
def scale(a, v):
    return [a * vi for vi in v]

def sumvector(v, w):
    return [vi + wi for vi, wi in zip(v, w)]

def dotvector(v, w):
    return sum(vi * wi for vi, wi in zip(v, w))

def lenvector(v):
    return dotvector(v, v)

# Dữ liệu mẫu
v = [3, 5, 7]
w = [2, 4, 6]

# Kết quả
print("scale(10, v):", scale(10, v))          # [30, 50, 70]
print("sumvector(v, w):", sumvector(v, w))    # [5, 9, 13]
print("dotvector(v, w):", dotvector(v, w))    # 68
print("lenvector(w):", lenvector(w))          # 56


scale(10, v): [30, 50, 70]
sumvector(v, w): [5, 9, 13]
dotvector(v, w): 68
lenvector(w): 56


In [8]:
import numpy as np

scores = np.array([-1, 1, 2, -3, 5, -4])

labels_2class = np.select(
    [scores >= 0, scores < 0],
    ['so duong', 'so am'],
    default='khong xac dinh'
)
print("Phân loại 2 loại:", labels_2class)

scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])

labels_3class = np.select(
    [scores > 0, scores == 0, scores < 0],
    ['so duong', 'so 0', 'so am'],
    default='khong xac dinh'
)
print("Phân loại 3 loại:", labels_3class)

Phân loại 2 loại: ['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']
Phân loại 3 loại: ['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


In [7]:
#bài tập 3
# 1. Nạp thư viện
import numpy as np
from scipy import linalg, sparse
from sympy import symbols, Eq, solve

# 2. Khai báo ma trận D
D = np.asmatrix([[3, 4], [5, 6]])
print("Ma trận D:")
print(D)

# 3. Tạo ma trận ngẫu nhiên 5x7
C = np.asmatrix(np.random.random((5, 7)))
print("\nMa trận C (5x7):")
print(C)

# 4. Tạo ma trận ngẫu nhiên 2x2
A = np.asmatrix(np.random.random((2, 2)))
print("\nMa trận A (2x2):")
print(A)

# 5. Chuyển đổi array thành ma trận phức
b = np.array([(1+5j, 2j, 3j), (4, 5, 6)])
B = np.asmatrix(b)

print("\nArray b:")
print(b)
print("Ma trận B:")
print(B)

# 6. Chuyển vị và nghịch đảo
print("\nChuyển vị A.T:")
print(A.T)

print("\nNghịch đảo A.I hoặc scipy.linalg.inv(A):")
print(A.I)
print(linalg.inv(A))

# 7. Ma trận dưới và trên đường chéo
M = np.array([[-1, 3, 2], [0, -2, 1], [1, 5, -2]])

M_lower = np.tril(M)
print("\nMa trận dưới đường chéo:")
print(M_lower)

M_upper = np.triu(M)
print("\nMa trận trên đường chéo:")
print(M_upper)

# 8. Vector và ma trận đường chéo
v_diag = np.diag(M)
print("\nVector đường chéo:")
print(v_diag)

M_diag = np.diag(v_diag)
print("Ma trận đường chéo từ vector:")
print(M_diag)

# 9. Ma trận đơn vị
I2 = np.identity(2)
print("\nMa trận đơn vị I2:")
print(I2)

# 10. Giải hệ phương trình bằng Sympy
x, y, z = symbols('x y z')

# Tính x, y, z
z_val = solve(Eq(-z, 8))[0]          # z = -8
x_val = solve(Eq(x + z_val, 1))[0]   # x = 9
y_val = solve(Eq(y + 4, 5))[0]       # y = 1

print("\nGiải hệ phương trình:")
print(f"x = {x_val}, y = {y_val}, z = {z_val}")
# Kiểm tra lại các giá trị
print("\nKiểm tra lại:")
print("x/2 + 2 =", x_val/2 + 2)      # nên ra 6
print("2x =", 2 * x_val)             # nên ra 8
print("y + 4 =", y_val + 4)          # nên ra 5

# 11. So sánh hai ma trận
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[1, 2], [3, 4]])

print("\nSo sánh hai ma trận:")
print("array_equal:", np.array_equal(a1, a2))
print("array_equiv:", np.array_equiv(a1, a2))
print("allclose:", np.allclose(a1, a2))



Ma trận D:
[[3 4]
 [5 6]]

Ma trận C (5x7):
[[0.16866293 0.09640684 0.23029153 0.48174051 0.47924179 0.62490087
  0.49038995]
 [0.03920137 0.24744608 0.61505263 0.57051295 0.74496068 0.98138322
  0.58131364]
 [0.40241759 0.03223293 0.71201867 0.58583076 0.08817976 0.12299028
  0.16007079]
 [0.52137915 0.88077712 0.05695941 0.29759543 0.80364183 0.3584111
  0.81427523]
 [0.80508186 0.5352727  0.60575732 0.5713725  0.72564143 0.99243521
  0.41836832]]

Ma trận A (2x2):
[[0.07172882 0.92377014]
 [0.15264125 0.13391358]]

Array b:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Ma trận B:
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]

Chuyển vị A.T:
[[0.07172882 0.15264125]
 [0.92377014 0.13391358]]

Nghịch đảo A.I hoặc scipy.linalg.inv(A):
[[-1.01912954  7.03021615]
 [ 1.16165365 -0.54588155]]
[[-1.01912954  7.03021615]
 [ 1.16165365 -0.54588155]]

Ma trận dưới đường chéo:
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]

Ma trận trên đường chéo:
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]

Vector đường

In [6]:
#Thực hành 3.2
import numpy as np

# 1. Tạo ma trận A kích thước 6x6
A = np.reshape(np.arange(36.0), (6, 6))
print("Ma trận A ban đầu:")
print(A)

# 2. Tạo ma trận đơn vị I6 (6x6)
I6 = np.identity(6)
print("\nMa trận đơn vị I6:")
print(I6)

# 3. Kích thước của A
print("\nKích thước (số phần tử) của A:", A.size)

# 4. In đường chéo chính của A
print("Đường chéo của A:", np.diagonal(A))

# 5. Cộng ma trận A với ma trận đơn vị
A = A + I6
print("\nMa trận A sau khi cộng với I6:")
print(A)

# 6. Tạo vector vecB và nhân với A
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print("\nVector vecB:")
print(vecB)
print("Kết quả C = A . vecB:")
print(C)

# 7. Tạo ma trận D (2x6)
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print("\nMa trận D (2x6):")
print(D)

# 8. Tính tích A . D^T (D phải chuyển vị thành 6x2 để nhân được)
E = A.dot(D.T)
print("Kết quả E = A . D.T:")
print(E)

# 9. Tạo ma trận F (6x2)
F = np.array([
    [1., 1.],
    [2., 0.],
    [3., 1.],
    [4., 0.],
    [5., 1.],
    [6., 0.]
])
print("\nMa trận F (6x2):")
print(F)

# 10. Tính G = A . F
G = A.dot(F)
print("Kết quả G = A . F:")
print(G)

# 11. Tính ma trận nghịch đảo của A
try:
    invA = np.linalg.inv(A)
    print("\nMa trận nghịch đảo của A:")
    print(invA)
except np.linalg.LinAlgError:
    print("\nA không khả nghịch, không thể tính nghịch đảo.")

# 12. Tính inv(inv(A)) để kiểm tra kết quả
try:
    A_restored = np.linalg.inv(np.linalg.inv(A))
    print("\ninv(inv(A)) (khôi phục lại A):")
    print(A_restored)
except np.linalg.LinAlgError:
    print("\nKhông thể tính inv(inv(A)) do A không khả nghịch.")


Ma trận A ban đầu:
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Ma trận đơn vị I6:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Kích thước (số phần tử) của A: 36
Đường chéo của A: [ 0.  7. 14. 21. 28. 35.]

Ma trận A sau khi cộng với I6:
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]

Vector vecB:
[1. 2. 3. 4. 5. 6.]
Kết quả C = A . vecB:
[ 71. 198. 325. 452. 579. 706.]

Ma trận D (2x6):
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
Kết quả E = A . D.T:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]

Ma trận F (6x2):
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
Kết quả G = A . F:
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [57

In [5]:
#Thực hành 4
import numpy as np
# Ma trận chuyển trạng thái cho dãy Fibonacci
A = np.array([[1, 1],
              [1, 0]])
# Vector trạng thái ban đầu (I_1 = 1, I_0 = 0)
b = np.array([1, 0])
# Số lượng số Fibonacci muốn tính (11 số)
n = 11
print("11 số Fibonacci đầu tiên theo mô hình ma trận tuyến tính:")
for i in range(n):
    b = A.dot(b)
    print(b[0])


11 số Fibonacci đầu tiên theo mô hình ma trận tuyến tính:
1
2
3
5
8
13
21
34
55
89
144


In [1]:
#Thực hành 5.2
import sympy as sp

# Định nghĩa biến
x1, x2, x3, x4 = sp.symbols('x1 x2 x3 x4')

# Viết lại các phương trình từ đề bài
pt1 = x4 + 610 - 450 - x1        # x4 + 610 - 450 - x1 = 0 → x4 - x1 + 160 = 0
pt2 = x1 + 400 - x2 - 640        # x1 - x2 - 240 = 0
pt3 = x2 + 600 - x3              # x2 - x3 + 600 = 0
pt4 = x3 - x4 - 520              # x3 - x4 - 520 = 0

# Giải hệ phương trình
nghiem = sp.solve((pt1, pt2, pt3, pt4), (x1, x2, x3, x4))
print("Nghiệm tìm được bằng sympy.solve:")
print(nghiem)

import numpy as np

A = np.matrix([
    [-1,  0,  0,  1],
    [ 1, -1,  0,  0],
    [ 0,  1, -1,  0],
    [ 0,  0,  1, -1]
])

# Kiểm tra định thức
det_A = np.linalg.det(A)
print(f"Định thức của A: {det_A}")

if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("Ma trận nghịch đảo A⁻¹ là:")
    print(np.round(A_inv, 2))
else:
    print(" Ma trận A không khả nghịch vì định thức = 0.")



Nghiệm tìm được bằng sympy.solve:
{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}
Định thức của A: 0.0
 Ma trận A không khả nghịch vì định thức = 0.


Bài tập về nhà

In [4]:
#Bâì tập 1
import numpy as np
# Problem 1: Giao điểm hai đường thẳng trong R²
# x - y = -2
# 2x + 3y = 6
A1 = np.array([[1, -1], [2, 3]])
b1 = np.array([-2, 6])
x1 = np.linalg.solve(A1, b1)
print("Problem 1 - Giao điểm hai đường thẳng (R²):")
print("x =", x1[0], ", y =", x1[1])
print()
# Problem 2: Giao điểm ba mặt phẳng trong R³
# x - y = 2
# 2x - y - z = 3
# x + y + z = 6
A2 = np.array([
    [1, -1, 0],
    [2, -1, -1],
    [1, 1, 1]
])
b2 = np.array([2, 3, 6])
x2 = np.linalg.solve(A2, b2)
print("Problem 2 - Giao điểm ba mặt phẳng (R³):")
print("x =", x2[0], ", y =", x2[1], ", z =", x2[2])
print()
# Problem 3: Tìm đa thức p(x) = ax² + bx + c thỏa:
# p(1) = 4, p(2) = 3, p(3) = 4
# => hệ:
# a + b + c = 4
# 4a + 2b + c = 3
# 9a + 3b + c = 4
A3 = np.array([
    [1, 1, 1],
    [4, 2, 1],
    [9, 3, 1]
])
b3 = np.array([4, 3, 4])
x3 = np.linalg.solve(A3, b3)
print("Problem 3 - Hệ số đa thức p(x) = ax² + bx + c:")
print("a =", x3[0], ", b =", x3[1], ", c =", x3[2])
print()
# Problem 4: Phân tích phân thức, tìm a, b, c thỏa:
# a + c = 1
# a + b - 2c = -3
# -2a + 2b + c = 0
A4 = np.array([
    [1, 0, 1],
    [1, 1, -2],
    [-2, 2, 1]
])
b4 = np.array([1, -3, 0])
x4 = np.linalg.solve(A4, b4)
print("Problem 4 - Hệ số a, b, c trong phân tích phân thức:")
print("a =", x4[0], ", b =", x4[1], ", c =", x4[2])


Problem 1 - Giao điểm hai đường thẳng (R²):
x = 0.0 , y = 2.0

Problem 2 - Giao điểm ba mặt phẳng (R³):
x = 3.0 , y = 1.0 , z = 2.0

Problem 3 - Hệ số đa thức p(x) = ax² + bx + c:
a = 1.0000000000000004 , b = -4.000000000000001 , c = 7.000000000000001

Problem 4 - Hệ số a, b, c trong phân tích phân thức:
a = -0.11111111111111105 , b = -0.6666666666666666 , c = 1.1111111111111112


In [3]:
#Bài tập 2
import sympy as sp

# Problem 1: Giao điểm hai đường thẳng trong R²
x, y = sp.symbols('x y')
pt1 = x - y + 2
pt2 = 2*x + 3*y - 6
nghiem1 = sp.solve((pt1, pt2), (x, y))
print("Problem 1 – Giao điểm hai đường thẳng (R²):")
print(nghiem1)
print()
# Problem 2: Giao điểm ba mặt phẳng trong R³
x, y, z = sp.symbols('x y z')
pt1 = x - y - 2
pt2 = 2*x - y - z - 3
pt3 = x + y + z - 6
nghiem2 = sp.solve((pt1, pt2, pt3), (x, y, z))
print("Problem 2 – Giao điểm ba mặt phẳng (R³):")
print(nghiem2)
print()
# Problem 3: Tìm hệ số đa thức bậc 2 p(x) = ax² + bx + c
a, b, c = sp.symbols('a b c')
pt1 = a*1**2 + b*1 + c - 4
pt2 = a*2**2 + b*2 + c - 3
pt3 = a*3**2 + b*3 + c - 4
nghiem3 = sp.solve((pt1, pt2, pt3), (a, b, c))
print("Problem 3 – Hệ số đa thức p(x) = ax² + bx + c:")
print(nghiem3)
print()
# Problem 4: Phân tích phân thức – Tìm a, b, c
a, b, c = sp.symbols('a b c')
pt1 = a + c - 1
pt2 = a + b - 2*c + 3
pt3 = -2*a + 2*b + c
nghiem4 = sp.solve((pt1, pt2, pt3), (a, b, c))
print("Problem 4 – Hệ số a, b, c trong phân tích phân thức:")
print(nghiem4)


Problem 1 – Giao điểm hai đường thẳng (R²):
{x: 0, y: 2}

Problem 2 – Giao điểm ba mặt phẳng (R³):
{x: 3, y: 1, z: 2}

Problem 3 – Hệ số đa thức p(x) = ax² + bx + c:
{a: 1, b: -4, c: 7}

Problem 4 – Hệ số a, b, c trong phân tích phân thức:
{a: -1/9, b: -2/3, c: 10/9}


In [2]:
#Bài tập 3
import numpy as np

# Hàm tạo dãy Fibonacci đến chỉ số n
def fibonacci(n):
    fib = [0, 1]
    for i in range(2, n + 2):
        fib.append(fib[-1] + fib[-2])
    return fib

# Hàm tính lũy thừa ma trận Fibonacci
def fib_matrix_power(k):
    F = np.array([[1, 1],
                  [1, 0]], dtype=object)
    F_k = np.linalg.matrix_power(F, k)
    return F_k

# In kết quả từ k = 1 đến 10 và kiểm tra giá trị
print("Lũy thừa ma trận Fibonacci F^k:\n")

for k in range(1, 11):
    F_k = fib_matrix_power(k)
    fib = fibonacci(k + 1)  # Tạo dãy Fibonacci đủ phần tử
    print(f"F^{k} =")
    print(F_k)
    print("So sánh với các số Fibonacci:")
    print(f"F_{k+1} = {fib[k+1]}, F_{k} = {fib[k]}, F_{k-1} = {fib[k-1]}")
    print(f"Các phần tử: [{F_k[0,0]}, {F_k[0,1]}; {F_k[1,0]}, {F_k[1,1]}]")
    print("-" * 40)



Lũy thừa ma trận Fibonacci F^k:

F^1 =
[[1 1]
 [1 0]]
So sánh với các số Fibonacci:
F_2 = 1, F_1 = 1, F_0 = 0
Các phần tử: [1, 1; 1, 0]
----------------------------------------
F^2 =
[[2 1]
 [1 1]]
So sánh với các số Fibonacci:
F_3 = 2, F_2 = 1, F_1 = 1
Các phần tử: [2, 1; 1, 1]
----------------------------------------
F^3 =
[[3 2]
 [2 1]]
So sánh với các số Fibonacci:
F_4 = 3, F_3 = 2, F_2 = 1
Các phần tử: [3, 2; 2, 1]
----------------------------------------
F^4 =
[[5 3]
 [3 2]]
So sánh với các số Fibonacci:
F_5 = 5, F_4 = 3, F_3 = 2
Các phần tử: [5, 3; 3, 2]
----------------------------------------
F^5 =
[[8 5]
 [5 3]]
So sánh với các số Fibonacci:
F_6 = 8, F_5 = 5, F_4 = 3
Các phần tử: [8, 5; 5, 3]
----------------------------------------
F^6 =
[[13 8]
 [8 5]]
So sánh với các số Fibonacci:
F_7 = 13, F_6 = 8, F_5 = 5
Các phần tử: [13, 8; 8, 5]
----------------------------------------
F^7 =
[[21 13]
 [13 8]]
So sánh với các số Fibonacci:
F_8 = 21, F_7 = 13, F_6 = 8
Các phần tử: [21, 