Bài tập

In [1]:
# Bài 1.1
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])  # Số phức
c = np.array([
    [(0.5, 1.5, 10), (3, 2, 1)],
    [(6, 5, 4), (7, 8, 9)]
])  # Ma trận số thực

# Các kiểu khai báo và khởi tạo ma trận
A = np.matrix(np.random.random((2, 2)))
B = np.asmatrix(b)
C = np.asmatrix(np.random.random((10, 5)))
D = np.asmatrix([[4, 3], [2, 6]])
F = np.eye(3, k=1)  # Đường chéo trên đường chéo chính

print("Ma trận F với k=1:")
print(F)
print()

# Thử một số câu lệnh liên quan:
F = np.eye(3, k=0)
print("Ma trận F với k=0:")
print(F)
print()

F = np.eye(3, k=-1)
print("Ma trận F với k=-1:")
print(F)
print()

# Các phép xử lý đơn giản

# Xem hạng ma trận
print("Hạng của ma trận C:")
print(np.linalg.matrix_rank(C))
print()

# Ma trận nghịch đảo
print("Nghịch đảo của A (A.I):")
print(A.I)
print()

print("Nghịch đảo của A bằng scipy.linalg.inv:")
print(linalg.inv(A))
print()

# Định thức ma trận
print("Định thức của A:")
print(linalg.det(A))
print()

# Chuyển vị ma trận
print("Chuyển vị A.T:")
print(A.T)
print()

print("Chuyển vị liên hợp A.H:")
print(A.H)
print()

# Giải phương trình tuyến tính
# Để tránh lỗi, tạo một vector b_simple có kích thước phù hợp:
b_simple = np.array([1, 2])
print("Giải hệ Ax = b_simple:")
print(linalg.solve(A, b_simple))
print()

# Tạo vector cột E từ a
E = np.asmatrix(a).T
print("Vector cột E:")
print(E)
print()

# Least Squares
print("Giải bình phương tối thiểu với lstsq:")
print(linalg.lstsq(F, E))
print()
# Các hàm trên ma trận
print("A + D:")
print(np.add(A, D))
print()

print("A - D:")
print(np.subtract(A, D))
print()

print("A / D:")
print(np.divide(A, D))
print()

print("A @ D:")
print(A @ D)
print()

print("np.multiply(D, A):")
print(np.multiply(D, A))
print()

print("np.dot(A, D):")
print(np.dot(A, D))
print()

print("np.vdot(A, D):")
print(np.vdot(A, D))
print()

# Hàm lũy thừa ma trận và logarit ma trận
print("expm(A):")
print(linalg.expm(A))
print()

print("logm(A):")
print(linalg.logm(A))
print()


Ma trận F với k=1:
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

Ma trận F với k=0:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Ma trận F với k=-1:
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

Hạng của ma trận C:
5

Nghịch đảo của A (A.I):
[[-1.22610593  4.65736807]
 [ 1.95113489 -1.920743  ]]

Nghịch đảo của A bằng scipy.linalg.inv:
[[-1.22610593  4.65736807]
 [ 1.95113489 -1.920743  ]]

Định thức của A:
-0.14854164168675293

Chuyển vị A.T:
[[0.28531032 0.28982478]
 [0.6918131  0.18212779]]

Chuyển vị liên hợp A.H:
[[0.28531032 0.28982478]
 [0.6918131  0.18212779]]

Giải hệ Ax = b_simple:
[ 8.0886302 -1.8903511]

Vector cột E:
[[1]
 [2]
 [3]]

Giải bình phương tối thiểu với lstsq:
(array([[2.],
       [3.],
       [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))

A + D:
[[4.28531032 3.6918131 ]
 [2.28982478 6.18212779]]

A - D:
[[-3.71468968 -2.3081869 ]
 [-1.71017522 -5.81787221]]

A / D:
[[0.07132758 0.23060437]
 [0.14491239 0.03035463]]

A @ D:
[[2.52486747 5.00680954]
 [1.52355469 1.96224106]

In [2]:
#bài 2.3
import numpy as np
# ================================
# Ma trận A
# ================================
print("=== MA TRẬN A ===")
A = np.array([[0, 1],
              [1, 0]])
print("Ma trận A:")
print(A)
print()

# Tính toán lần thứ nhất
temp = A.dot(A)
print("A.dot(A):")
print(temp)
print()

# Vòng lặp lũy thừa
k = 6
print(f"Nhân tiếp {k-1} lần với A:")
for i in range(k-1):
    temp = temp.dot(A)
    print(temp)
    print('---')

# ================================
# Ma trận B
# ================================
print("\n=== MA TRẬN B ===")
B = np.array([[0, -1],
              [-1, 0]])
print("Ma trận B:")
print(B)
print()

# Tính toán lần thứ nhất
temp = B.dot(B)
print("B.dot(B):")
print(temp)
print()

# Vòng lặp lũy thừa
k = 5
print(f"Nhân tiếp {k-1} lần với B:")
for i in range(k-1):
    temp = temp.dot(B)
    print(temp)
    print('---')
#c
import numpy as np

# Khai báo ma trận C
C = np.array([
    [1, 0, 0],
    [0, 0.5, 1],
    [0, 0, 0.5]
])
print("Ma trận C:")
print(C)
print()

# Tính lần đầu tiên: C^2
temp = np.dot(C, C)
print("C^2:")
print(temp)
print()

# Tính C^k với k = 1000
k = 1000
for i in range(k-1):
    temp = np.dot(temp, C)
print(f"C^{k}:")
print(temp)
print("\nNhận xét: Dễ thấy phần tử (1,1) giữ nguyên bằng 1, các giá trị còn lại tiến dần về 0 (theo ma trận hội tụ).")

# Tính tiếp thêm 1000 lần nữa để kiểm chứng
k2 = 1000
for i in range(k2-1):
    temp = np.dot(temp, C)
print(f"\nC^{k + k2 -1}:")
print(temp)
print("\nNhận xét: Ma trận hội tụ về ma trận chỉ có phần tử (1,1) = 1, các giá trị còn lại bằng 0.")

# Để tiện quan sát, có thể in thêm A vô hạn thủ công:
A_inf = np.zeros((3,3))
A_inf[0,0] = 1
print("\nMa trận hội tụ A^∞:")
print(A_inf)



=== MA TRẬN A ===
Ma trận A:
[[0 1]
 [1 0]]

A.dot(A):
[[1 0]
 [0 1]]

Nhân tiếp 5 lần với A:
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---

=== MA TRẬN B ===
Ma trận B:
[[ 0 -1]
 [-1  0]]

B.dot(B):
[[1 0]
 [0 1]]

Nhân tiếp 4 lần với B:
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
Ma trận C:
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]

C^2:
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]

C^1000:
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]

Nhận xét: Dễ thấy phần tử (1,1) giữ nguyên bằng 1, các giá trị còn lại tiến dần về 0 (theo ma trận hội tụ).

C^1999:
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Nhận xét: Ma trận hội tụ về ma trận chỉ có phần tử (1,1) = 1, các giá trị còn lại bằng 0.

Ma trận hội tụ A^∞:
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#Bài 2.4
import numpy as np

# Khai báo ma trận M
M = np.array([
    [0.8, 0.3],
    [0.2, 0.7]
])
print("Ma trận M:")
print(M)
print()

# Tính M^2
MM = M.dot(M)
print("M^2:")
print(MM)
print()

# Tính M^3
MM = MM.dot(M)
print("M^3:")
print(MM)
print()

# Tính M^k khi k lớn (ví dụ 100 lần)
for i in range(100):
    MM = MM.dot(M)
print("M^∞ (ước tính sau 100 lần nhân):")
print(MM)
print("\nNhận xét: Ma trận có xu hướng hội tụ về một ma trận có các cột giống nhau, phản ánh trạng thái ổn định của chuỗi Markov.")



Ma trận M:
[[0.8 0.3]
 [0.2 0.7]]

M^2:
[[0.7  0.45]
 [0.3  0.55]]

M^3:
[[0.65  0.525]
 [0.35  0.475]]

M^∞ (ước tính sau 100 lần nhân):
[[0.6 0.6]
 [0.4 0.4]]

Nhận xét: Ma trận có xu hướng hội tụ về một ma trận có các cột giống nhau, phản ánh trạng thái ổn định của chuỗi Markov.


In [4]:
#bài 3.2
import numpy as np
from scipy import linalg

# Bước 1: Khai báo ma trận M
M = np.array([
    [0.8, 0.3],
    [0.2, 0.7]
])
print("Ma trận M:")
print(M)
print()

# Bước 2: Phân rã LU
P, L, U = linalg.lu(M)

# Bước 3: In ra các ma trận
print("Ma trận P (Permutation matrix):")
print(P)
print()

print("Ma trận L (Lower triangular):")
print(L)
print()

print("Ma trận U (Upper triangular):")
print(U)
print()

# Bước 4: Kiểm tra lại: L.dot(U) có bằng M ban đầu không?
print("L.dot(U):")
print(L.dot(U))
print()

print("Nhận xét: Kết quả của L.dot(U) (sau hoán vị nếu cần thiết với P) khớp với M.")


Ma trận M:
[[0.8 0.3]
 [0.2 0.7]]

Ma trận P (Permutation matrix):
[[1. 0.]
 [0. 1.]]

Ma trận L (Lower triangular):
[[1.   0.  ]
 [0.25 1.  ]]

Ma trận U (Upper triangular):
[[0.8   0.3  ]
 [0.    0.625]]

L.dot(U):
[[0.8 0.3]
 [0.2 0.7]]

Nhận xét: Kết quả của L.dot(U) (sau hoán vị nếu cần thiết với P) khớp với M.


In [5]:
#bài 5
#
import numpy as np

A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])
print("Ma trận A:")
print(A)
print()

# A^2
temp = A.dot(A)
print("Ma trận A^2:")
print(temp)
print()

# A^3
temp = temp.dot(A)
print("Ma trận A^3:")
print(temp)





Ma trận A:
[[0 1 0 1]
 [0 0 1 0]
 [1 0 0 1]
 [1 1 0 0]]

Ma trận A^2:
[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]

Ma trận A^3:
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [6]:
#Bài 5.2
import numpy as np

A = np.array([
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [1, 0, 0, 1],
    [1, 1, 0, 0]
])
sumA = A
temp = A.dot(A)  # A^2
k = 3
sumA = sumA + temp  # sumA = A + A^2

for i in range(1, k-1):  # i từ 1 đến 1 (vì k=3, k-1=2)
    temp = temp.dot(A)  # temp = A^3
    sumA = sumA + temp

print(temp)   # A^3
print(sumA)   # A + A^2 + A^3


[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


Bài tập về nhà

In [ ]:
# Bài1
import numpy as np

def is_invertible(matrix):
    return np.linalg.det(matrix) != 0

def text_to_numbers(text):
    # Chuyển chữ cái thành số: A=0, B=1,..., Z=25, space=26 (ví dụ)
    text = text.upper()
    mapping = {chr(i + 65): i for i in range(26)}
    mapping[' '] = 26
    numbers = [mapping.get(ch, 26) for ch in text]  # ký tự không trong A-Z -> space
    return numbers

def numbers_to_text(numbers):
    rev_map = {i: chr(i + 65) for i in range(26)}
    rev_map[26] = ' '
    text = ''.join([rev_map.get(num, ' ') for num in numbers])
    return text

def pad_numbers(numbers, block_size):
    # Đệm số lượng phần tử sao cho chia hết cho block_size
    while len(numbers) % block_size != 0:
        numbers.append(26)  # thêm space
    return numbers

def encrypt(matrix, numbers):
    n = matrix.shape[0]
    numbers = pad_numbers(numbers, n)
    encrypted = []
    for i in range(0, len(numbers), n):
        block = np.array(numbers[i:i+n])
        enc_block = matrix.dot(block) % 27  # modulo 27 để tránh số quá lớn
        encrypted.extend(enc_block.astype(int))
    return encrypted

def decrypt(matrix_inv, encrypted):
    n = matrix_inv.shape[0]
    decrypted = []
    for i in range(0, len(encrypted), n):
        block = np.array(encrypted[i:i+n])
        dec_block = matrix_inv.dot(block) % 27
        decrypted.extend(np.round(dec_block).astype(int))
    return decrypted

def main():
    # a) Chọn ma trận khả nghịch 3x3
    A = np.array([
        [2, 4, 5],
        [9, 2, 1],
        [3, 17, 7]
    ])
    print("Ma trận A:\n", A)

    det = np.linalg.det(A)
    print("Định thức của A:", det)
    if abs(det) < 1e-10:
        print("Ma trận không khả nghịch!")
        return

    A_inv = np.linalg.inv(A)
    print("Ma trận nghịch đảo A_inv:\n", A_inv)

    # b) Nhập họ tên hoặc mã số sinh viên
    text = input("Nhập họ tên hoặc mã số sinh viên: ")

    # c) Mã hóa
    numbers = text_to_numbers(text)
    print("Dãy số sau khi mã hóa ký tự:", numbers)

    encrypted = encrypt(A, numbers)
    print("Dữ liệu đã mã hóa:", encrypted)

    # d) Giải mã
    decrypted = decrypt(A_inv, encrypted)
    print("Dữ liệu đã giải mã (dạng số):", decrypted)

    text_decrypted = numbers_to_text(decrypted)
    print("Chuỗi sau khi giải mã:", text_decrypted)

if __name__ == "__main__":
    main()


Ma trận A:
 [[ 2  4  5]
 [ 9  2  1]
 [ 3 17  7]]
Định thức của A: 488.9999999999997
Ma trận nghịch đảo A_inv:
 [[-0.00613497  0.11656442 -0.01226994]
 [-0.12269939 -0.00204499  0.08793456]
 [ 0.3006135  -0.04498978 -0.06543967]]


In [ ]:
#Bài 2
def continued_fraction(coeffs):
    p0, p1 = coeffs[0], coeffs[0]*coeffs[1] + 1 if len(coeffs) > 1 else 1
    q0, q1 = 1, coeffs[1] if len(coeffs) > 1 else 0

    for i in range(2, len(coeffs)):
        p = coeffs[i]*p1 + p0
        q = coeffs[i]*q1 + q0
        p0, p1 = p1, p
        q0, q1 = q1, q

    return p1, q1

# Ví dụ:
coeffs = [3, 1, 2]  # biểu diễn 11/3
p, q = continued_fraction(coeffs)
print(f"{p}/{q}")  # Output: 11/3
