#Bài tập

In [1]:
#1.3
from numpy import matlib

# Tạo ma trận đơn vị kích thước 5x5
G = matlib.identity(5)
print("Ma trận đơn vị G (5x5):")
print(G)

# Tạo ma trận ngẫu nhiên 3x2 (phân phối chuẩn)
H = matlib.randn(3, 2)
print("\nMa trận ngẫu nhiên H (3x2):")
print(H)

# Tạo ma trận không (zero) kích thước 4x4
K = matlib.zeros([4, 4])
print("\nMa trận không K (4x4):")
print(K)


Ma trận đơn vị G (5x5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Ma trận ngẫu nhiên H (3x2):
[[ 0.57738864  0.09733199]
 [ 2.5430551   1.4591588 ]
 [-1.37816276 -0.28916021]]

Ma trận không K (4x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
#Bài 2
from numpy import matlib

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]

for i in range(len(c)):
    ci = matlib.matrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M * ci   # <-- NHÂN NGƯỢC (từ trái qua phải)

print(M)
print('Số gần đúng của pi là: ',(M[0, 0] / M[1, 0]))


[[165707065  80143857]
 [ 52746197  25510582]]
Số gần đúng của pi là:  3.1415926535897936


In [12]:
#bài 3
import numpy as np

# Nhập dữ liệu X và Y
X = np.array([[1, 1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])

Y = np.array([[1],
              [2],
              [2],
              [4],
              [5]])

# Tính X^T
XT = X.T

# Tính A1 = (X^T * X)^(-1)
A1 = np.linalg.inv(XT.dot(X))

# Tính A2 = X^T * Y
A2 = XT.dot(Y)

# Tính A = A1 * A2
A = A1.dot(A2)

# In kết quả hệ số a0 và a1
print("Hệ số hồi quy:")
print(f"a0 = {A[0,0]:.2f}")
print(f"a1 = {A[1,0]:.2f}")

# Hàm f(x) = a0 + a1 * x
def f(x):
    return A[0,0] + A[1,0] * x

# Tính giá trị dự đoán và sai số bình phương
print("\nSai số bình phương tại từng điểm:")
squared_errors = []
for i in range(len(X)):
    xi = X[i, 1]
    yi = Y[i, 0]
    fi = f(xi)
    error = (fi - yi) ** 2
    print(f"f({xi}) = {fi:.2f}, y = {yi}, sai số bình phương = {error:.2f}")
    squared_errors.append(error)

# Tổng sai số bình phương
print(f"\nTổng sai số bình phương: {sum(squared_errors):.2f}")


Hệ số hồi quy:
a0 = -0.20
a1 = 1.00

Sai số bình phương tại từng điểm:
f(1) = 0.80, y = 1, sai số bình phương = 0.04
f(2) = 1.80, y = 2, sai số bình phương = 0.04
f(3) = 2.80, y = 2, sai số bình phương = 0.64
f(4) = 3.80, y = 4, sai số bình phương = 0.04
f(5) = 4.80, y = 5, sai số bình phương = 0.04

Tổng sai số bình phương: 0.80


#bài tập về nhà


In [13]:
import numpy as np

def bpcuctieu(a):
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)
        b.append(i * 1.0)  # thời gian từ 0,1,2,... (không phải i+1)

    x = np.array([o1, b])  # tạo ma trận X gồm 2 hàng: [1,1,1,...], [0,1,2,...]
    u = np.dot(x, x.T)     # nhân x với x.T (2xN · Nx2 = 2x2)

    y = np.array(a)        # y là lượng thuốc còn lại tại từng thời điểm

    from numpy import linalg
    u_inv = np.linalg.inv(u)        # (X·Xᵗ)⁻¹
    v = np.dot(u_inv, x)            # (X·Xᵗ)⁻¹ · X

    A = np.dot(v, y)                # A = [(a₀), (a₁)] — hệ số hồi quy
    return A

# Dữ liệu lượng thuốc tại các thời điểm t = 0 đến 4
dulieu = [10.0, 8, 7, 5, 2]

# Gọi hàm để tính hệ số hồi quy
A = bpcuctieu(dulieu)

# In kết quả phương trình tuyến tính
a0 = A[0]
a1 = A[1]

print(f"Phương trình tuyến tính là: y = {a0:.1f} + ({a1:.1f})·t")


Phương trình tuyến tính là: y = 10.2 + (-1.9)·t
