#Bài tập

In [2]:
import math
import numpy as np
from scipy import linalg

# Hàm tính chuẩn đã cho
def chuan(v, k):
    tong = 0
    for i in range(len(v)):
        tong = tong + abs(v[i])**k
    ketqua = math.pow(tong, 1.0/k)
    return ketqua

# Vector 'a'
a = np.array([1, 2, -3])

# In ra kết quả cho từng dòng lệnh như yêu cầu
print(f"np.linalg.norm(a): {np.linalg.norm(a)}")
print(f"np.linalg.norm(a, 1): {np.linalg.norm(a, 1)}")

print(f"chuan(a, 1): {chuan(a, 1)}")
print(f"np.linalg.norm(a, 1): {np.linalg.norm(a, 1)}")

print(f"chuan(a, 2): {chuan(a, 2)}")
print(f"np.linalg.norm(a, 2): {np.linalg.norm(a, 2)}")

print(f"chuan(a, 3): {chuan(a, 3)}")
print(f"np.linalg.norm(a, 3): {np.linalg.norm(a, 3)}")

print(f"chuan(a, 1000): {chuan(a, 1000)}")
print(f"np.linalg.norm(a, 1000): {np.linalg.norm(a, 1000)}")

print(f"linalg.norm(a): {linalg.norm(a)}")
print(f"linalg.norm(a, 100): {linalg.norm(a, 100)}")
print(f"linalg.norm(a, 1000): {linalg.norm(a, 1000)}")

# Giải thích ngắn gọn về lỗi
print("Lỗi nếu k quá lớn: Hàm 'chuan' có thể tràn số nếu các giá trị quá lớn.")
print("Tuy nhiên, với vector 'a' này, không có lỗi. Kết quả cho k lớn sẽ gần bằng 3.")

np.linalg.norm(a): 3.7416573867739413
np.linalg.norm(a, 1): 6.0
chuan(a, 1): 6.0
np.linalg.norm(a, 1): 6.0
chuan(a, 2): 3.7416573867739413
np.linalg.norm(a, 2): 3.7416573867739413
chuan(a, 3): 3.3019272488946263
np.linalg.norm(a, 3): 3.3019272488946263
chuan(a, 1000): 1.0442214818467515
np.linalg.norm(a, 1000): inf
linalg.norm(a): 3.7416573867739413
linalg.norm(a, 100): 3.0
linalg.norm(a, 1000): inf
Lỗi nếu k quá lớn: Hàm 'chuan' có thể tràn số nếu các giá trị quá lớn.
Tuy nhiên, với vector 'a' này, không có lỗi. Kết quả cho k lớn sẽ gần bằng 3.


In [3]:
import numpy as np

# 1. Khai báo ma trận chuyển trạng thái A
# Từ phương trình:
# xt+1 = q*xt + p*yt
# yt+1 = (1-q)*xt + (1-p)*yt
# Với p = 0.136 và q = 0.998
p = 0.136
q = 0.998
A = np.array([[q, p],
              [1-q, 1-p]])
print(f"Ma trận A:\n{A}")

# 2. Khai báo vector trạng thái ban đầu v0 (t=0)
# x0 = 0.95 (có việc làm)
# y0 = 0.05 (thất nghiệp)
v0 = np.array([[0.95],
               [0.05]])
print(f"\nVector trạng thái ban đầu v0:\n{v0}")

# 3. Tính ma trận A^100 (A mũ 100)
# Sử dụng np.linalg.matrix_power để tính lũy thừa ma trận
A_100 = np.linalg.matrix_power(A, 100)
print(f"\nMa trận A^100:\n{A_100}")

# 4. Tính vector x100 và y100 (trạng thái sau 100 tuần)
# v100 = A^100 * v0
v100 = np.dot(A_100, v0)
print(f"\nVector trạng thái sau 100 tuần (x100, y100):\n{v100}")

# In riêng x100 và y100
x100 = v100[0, 0]
y100 = v100[1, 0]
print(f"\nGiá trị x100 (tỷ lệ có việc làm sau 100 tuần): {x100:.6f}")
print(f"Giá trị y100 (tỷ lệ thất nghiệp sau 100 tuần): {y100:.6f}")

Ma trận A:
[[0.998 0.136]
 [0.002 0.864]]

Vector trạng thái ban đầu v0:
[[0.95]
 [0.05]]

Ma trận A^100:
[[0.98550725 0.9855069 ]
 [0.01449275 0.0144931 ]]

Vector trạng thái sau 100 tuần (x100, y100):
[[0.98550723]
 [0.01449277]]

Giá trị x100 (tỷ lệ có việc làm sau 100 tuần): 0.985507
Giá trị y100 (tỷ lệ thất nghiệp sau 100 tuần): 0.014493


In [6]:
import sympy as sym

# Define symbolic variables
x, y = sym.symbols('x y')

xy = sym.Matrix([x, y])

A_sym_system = sym.Matrix([[1, -68], [1, 1]])
v_sym_system = sym.Matrix([0, 1])


nghiem_sym = sym.solve(A_sym_system * xy - v_sym_system, (x, y))

print("--- Kết quả từ Sympy ---")
print(sym.pretty(nghiem_sym))

x_sym = nghiem_sym[x]
y_sym = nghiem_sym[y]

print(f"Giá trị x (Sympy): {x_sym}")
print(f"Giá trị y (Sympy): {y_sym}")

y_percentage_sym = float(y_sym) * 100
print(f"Tỷ lệ thất nghiệp sau 100 tuần (Sympy): y = {y_sym} = {y_percentage_sym:.2f}%")

--- Kết quả từ Sympy ---
⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭
Giá trị x (Sympy): 68/69
Giá trị y (Sympy): 1/69
Tỷ lệ thất nghiệp sau 100 tuần (Sympy): y = 1/69 = 1.45%


In [8]:
import numpy as np

A = np.array([[1, 6],
              [5, 2]])
print(f"Ma trận A:\n{A}")

u = np.array([[6],
              [-5]])
print(f"\nVector riêng u:\n{u}")

Au = np.dot(A, u)
print(f"\nKết quả của Au:\n{Au}")

neg_4u = -4 * u
print(f"\nKết quả của -4u:\n{neg_4u}")

if np.array_equal(Au, neg_4u):
    print("\nAu = -4u đã được chứng minh: Giá trị riêng và vector riêng là đúng.")
else:
    print("\nCó lỗi trong việc chứng minh Au = -4u.")

Ma trận A:
[[1 6]
 [5 2]]

Vector riêng u:
[[ 6]
 [-5]]

Kết quả của Au:
[[-24]
 [ 20]]

Kết quả của -4u:
[[-24]
 [ 20]]

Au = -4u đã được chứng minh: Giá trị riêng và vector riêng là đúng.


In [14]:
import numpy as np
from numpy import linalg as LA

# 1. Khai báo các ma trận A, D, P
A = np.array([[2, 3],
              [3, -6]])

D = np.array([[-7.0, 0],
              [0, 3.0]])

P = np.array([[-1.0/3, 3],
              [1, 1]])

# 2. Tính P^-1
P1 = LA.inv(P)
print(f"P^-1:\n{P1}")

# 3. Kiểm tra A.dot(P) và P.dot(D)
print(f"\nA.dot(P):\n{np.dot(A, P)}")
print(f"P.dot(D):\n{np.dot(P, D)}")

# 4. Tính D**2
print(f"\nD**2:\n{D**2}")

# 5. Tính A^1000
import numpy as np
from numpy import linalg as LA

A = np.array([[2, 3], [3, -6]])
D = np.array([[-7.0, 0], [0, 3.0]])
P = np.array([[-1.0/3, 3], [1, 1]])
P1 = LA.inv(P)

# Thử với số mũ nhỏ hơn, ví dụ 10
A_10 = P @ (D ** 10) @ P1
print(f"\nA^10:\n{A_10}")

P^-1:
[[-0.3  0.9]
 [ 0.3  0.1]]

A.dot(P):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
P.dot(D):
[[ 2.33333333  9.        ]
 [-7.          3.        ]]

D**2:
[[49.  0.]
 [ 0.  9.]]

A^10:
[[ 2.83006690e+07 -8.47248600e+07]
 [-8.47248600e+07  2.54233629e+08]]


#Bài tập về nhà

In [15]:
import numpy as np
import math

# CÂU 1: Tính chuẩn 2 của vector a
a = np.array([1, 2, 3])

# Cách 1: dùng dot
mag1 = np.sqrt(a.dot(a))

# Cách 2: dùng toán tử @
mag2 = np.sqrt(a @ a)

# Cách 3: dùng np.inner
mag3 = np.sqrt(np.inner(a, a))

# Cách 4: dùng lambda với math
mag_func = lambda x: math.sqrt(sum(i**2 for i in x))
mag4 = mag_func(a)

print("Câu 1:")
print("Chuẩn 2 (cách 1):", mag1)
print("Chuẩn 2 (cách 2):", mag2)
print("Chuẩn 2 (cách 3):", mag3)
print("Chuẩn 2 (cách 4):", mag4)


Câu 1:
Chuẩn 2 (cách 1): 3.7416573867739413
Chuẩn 2 (cách 2): 3.7416573867739413
Chuẩn 2 (cách 3): 3.7416573867739413
Chuẩn 2 (cách 4): 3.7416573867739413


In [16]:
#câu 2
import numpy as np

# Nhập vector u và v
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# a. Tính khoảng cách giữa 2 vector u và v
distance = np.linalg.norm(u - v)
print("a. Khoảng cách giữa u và v:", distance)

# b. Tính góc θ giữa u và v
dot_product = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
cos_theta = dot_product / (norm_u * norm_v)
theta = np.arccos(cos_theta)
print("b. Góc giữa u và v (radian):", theta)

# c. Phép chiếu trực giao của p lên v
projection = (np.dot(u, v) / np.dot(v, v)) * v
print("c. Vector chiếu trực giao của u lên v:", projection)


a. Khoảng cách giữa u và v: 5.196152422706632
b. Góc giữa u và v (radian): 0.2257261285527342
c. Vector chiếu trực giao của u lên v: [1.66233766 2.07792208 2.49350649]
