#Bài tập tại lớp

Bài 1

In [6]:
#Bài 1.1
import numpy as np
# Khai báo vector
u = np.array([2, -1, 5, 0])
v = np.array([4, 3, 1, -1])
w = np.array([-6, 2, 0, 3])
# Câu a: x = 2u - (v + 3w)
x_a = 2 * u - (v + 3 * w)
print("Câu a - Vector x =", x_a)
# Câu b: Giải phương trình 3(x + w) = 2u - v + x
# => 2x = 2u - v - 3w => x = 0.5 * (2u - v - 3w)
x_b = 0.5 * (2 * u - v - 3 * w)
print("Câu b - Vector x =", x_b)

Câu a - Vector x = [ 18 -11   9  -8]
Câu b - Vector x = [ 9.  -5.5  4.5 -4. ]


In [7]:
#Bài 1.2
import numpy as np
from numpy import linalg

# Ma trận hệ số A từ hệ phương trình:
A = np.matrix([
    [0, -1, 3],
    [1, 1, 1],
    [4, 2, 2]
])

# Vector vế phải B
B = np.array([-1, -2, -2])

# Giải hệ phương trình tuyến tính AX = B
X = np.linalg.solve(A, B)

print("Giá trị của a, b, c lần lượt là:")
print(X)

# Kết luận x = a*u + b*v + c*w
a, b, c = X
print(f"\nVậy: x = {a}*u + {b}*v + {c}*w")

Giá trị của a, b, c lần lượt là:
[ 1. -2. -1.]

Vậy: x = 1.0*u + -2.0*v + -1.0*w


In [8]:
#Bài 1.3
import numpy as np
from numpy import linalg as LA

# Khai báo 2 ma trận không khả nghịch (det = 0)
A = np.matrix([[1.0, 0], [0, 0]])
B = np.matrix([[0, 0], [0, 1.0]])

print("=== Phương pháp 1: Dùng LA.inv để kiểm tra khả nghịch ===")
try:
    inv_A = LA.inv(A)
    print("A khả nghịch")
except LA.LinAlgError:
    print("A không khả nghịch (gây ra lỗi)")

try:
    inv_B = LA.inv(B)
    print("B khả nghịch")
except LA.LinAlgError:
    print("B không khả nghịch (gây ra lỗi)")

try:
    inv_A_plus_B = LA.inv(A + B)
    print("A + B khả nghịch")
except LA.LinAlgError:
    print("A + B không khả nghịch (gây ra lỗi)")

print("\n=== Phương pháp 2: Kiểm tra định thức ===")
det_A = LA.det(A)
det_B = LA.det(B)
det_A_plus_B = LA.det(A + B)

print(f"det(A) = {det_A}")
print(f"det(B) = {det_B}")
print(f"det(A + B) = {det_A_plus_B}")

=== Phương pháp 1: Dùng LA.inv để kiểm tra khả nghịch ===
A không khả nghịch (gây ra lỗi)
B không khả nghịch (gây ra lỗi)
A + B khả nghịch

=== Phương pháp 2: Kiểm tra định thức ===
det(A) = 0.0
det(B) = 0.0
det(A + B) = 1.0


In [9]:
#Bài 1.4
import sympy as sp
# Khai báo biến x, y
x, y = sp.symbols('x y')
# Tạo ma trận A đối xứng
A = sp.Matrix([[x, y], [y, x]])
print("Ma trận A:")
sp.pprint(A)
# Kiểm tra chuyển vị
print("\nA.T (ma trận chuyển vị của A):")
sp.pprint(A.T)
# Kiểm tra A == A.T
print("\nA có bằng A.T không?")
print(A.equals(A.T))  # True nếu đối xứng
# Phần kiểm chứng tính đóng (A1 + A2)
x1, y1 = sp.symbols('x1 y1')
x2, y2 = sp.symbols('x2 y2')
A1 = sp.Matrix([[x1, y1], [y1, x1]])
A2 = sp.Matrix([[x2, y2], [y2, x2]])
print("\nMa trận A1 + A2:")
sp.pprint(A1 + A2)
print("\n(A1 + A2).T có bằng A1 + A2 không?")
print((A1 + A2).T.equals(A1 + A2))  # True nếu tổng vẫn đối xứng
# Kiểm tra c*A có đối xứng không
c = sp.symbols('c')
print("\nc * A:")
print(c * A)
print("\n(c * A).T có bằng c * A không?")
print(((c * A).T).equals(c * A))  # True nếu đúng

Ma trận A:
⎡x  y⎤
⎢    ⎥
⎣y  x⎦

A.T (ma trận chuyển vị của A):
⎡x  y⎤
⎢    ⎥
⎣y  x⎦

A có bằng A.T không?
True

Ma trận A1 + A2:
⎡x₁ + x₂  y₁ + y₂⎤
⎢                ⎥
⎣y₁ + y₂  x₁ + x₂⎦

(A1 + A2).T có bằng A1 + A2 không?
True

c * A:
Matrix([[c*x, c*y], [c*y, c*x]])

(c * A).T có bằng c * A không?
True


In [10]:
#Bài 1.5
import sympy as sp

# Khai báo biến
c1, c2, c3 = sp.symbols('c1 c2 c3')

# Tạo 3 phương trình từ đẳng thức: c1*v1 + c2*v2 + c3*v3 = 0
eq1 = c1 - 2*c3             # Thành phần x
eq2 = 2*c1 + c2             # Thành phần y
eq3 = 3*c1 + 2*c2 + c3      # Thành phần z

# Giải hệ phương trình
solution = sp.linsolve([eq1, eq2, eq3], (c1, c2, c3))
print("Nghiệm:", solution)


Nghiệm: {(0, 0, 0)}


In [11]:
#Bài 1.6'
import sympy as sp

# Khai báo 3 ẩn c1, c2, c3
c1, c2, c3 = sp.symbols('c1 c2 c3')

# Xây dựng hệ phương trình từ đẳng thức: c1*v1 + c2*v2 + c3*v3 = 0
eq1 = c1 - 2*c3             # Thành phần x: 1*c1 + 0*c2 + (-2)*c3 = 0
eq2 = 2*c1 + 1*c2 + 0*c3    # Thành phần y: 2*c1 + 1*c2 + 0*c3 = 0
eq3 = 3*c1 + 2*c2 + 1*c3    # Thành phần z: 3*c1 + 2*c2 + 1*c3 = 0

# Giải hệ phương trình
solution = sp.solve([eq1, eq2, eq3], (c1, c2, c3))
print("Nghiệm hệ phương trình là:", solution)


Nghiệm hệ phương trình là: {c1: 0, c2: 0, c3: 0}


In [12]:
#Bài 1.7
import sympy as sp

# Khai báo ẩn số
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')

# Hệ phương trình: c1 + c2 = u1 ; c1 - c2 = u2
eq1 = c1 + c2 - u1
eq2 = c1 - c2 - u2

# Giải hệ phương trình
solution = sp.solve([eq1, eq2], (c1, c2))
print("Giải hệ phương trình (tính sinh):")
print(solution)


Giải hệ phương trình (tính sinh):
{c1: u1/2 + u2/2, c2: u1/2 - u2/2}


Bài 2

In [13]:
#Bài 2
#a
import numpy as np

# Dữ liệu gốc (tọa độ các điểm)
P = np.array([[0, 0, 3, 3, 1, 1, 2, 2, 1, 1],
              [0, 5, 5, 4, 4, 3, 3, 2, 2, 0]])

# Vector tịnh tiến
vecdelta = np.array([4, 2])

# Áp dụng biến đổi tịnh tiến
P_caua = (P.T + vecdelta).T
print("Biến đổi tịnh tiến (P_caua):")
print(P_caua)
#b
# Ma trận biến đổi co giãn
matran_biendoi = np.array([[1.0, 0.0],
                           [0.0, 2.0]])

# Vector tịnh tiến
vecdelta = np.array([4, -2])

# Áp dụng phép co giãn + tịnh tiến
P_caub = (P.T @ matran_biendoi + vecdelta).T
print("Biến đổi tịnh tiến + co giãn (P_caub):")
print(P_caub)
#c
# Ma trận đối xứng qua trục y
matran_doitrucy = np.array([[-1, 0],
                            [ 0, 1]])

# Vector tịnh tiến
vecdelta = np.array([4, 2])

# Áp dụng phép đối xứng trục y + tịnh tiến
P_cauc = (P.T @ matran_doitrucy + vecdelta).T
print("Biến đổi tịnh tiến + đối xứng trục y (P_cauc):")
print(P_cauc)


Biến đổi tịnh tiến (P_caua):
[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]
Biến đổi tịnh tiến + co giãn (P_caub):
[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]
Biến đổi tịnh tiến + đối xứng trục y (P_cauc):
[[4 4 1 1 3 3 2 2 3 3]
 [2 7 7 6 6 5 5 4 4 2]]


#Bài tập chương

In [14]:
#Bài 1
import sympy as sp

x, y, z = sp.symbols('x y z')
u = sp.Matrix([x, y, z])
g = sp.Matrix([x + y, z + 2, 0])

# Kiểm tra tính tuyến tính: g(a*u + b*v) == a*g(u) + b*g(v)?
a, b = sp.symbols('a b')
v = sp.Matrix([1, 2, 3])  # lấy v bất kỳ

g1 = g.subs({x: a*x + b*v[0], y: a*y + b*v[1], z: a*z + b*v[2]})
g2 = a * g + b * g.subs({x: v[0], y: v[1], z: v[2]})
print("g(a*u + b*v):", g1)
print("a*g(u) + b*g(v):", g2)
print("Có bằng nhau không?", sp.simplify(g1 - g2) == sp.Matrix([0, 0, 0]))


g(a*u + b*v): Matrix([[a*x + a*y + 3*b], [a*z + 3*b + 2], [0]])
a*g(u) + b*g(v): Matrix([[a*(x + y) + 3*b], [a*(z + 2) + 5*b], [0]])
Có bằng nhau không? False


In [15]:
#Bài 2
import numpy as np

# Tập điểm F
F = np.array([[0, 0, 1, 1],
              [0, 1, 1, 0]])  # ví dụ là hình vuông đơn vị

# Ma trận biến đổi
A = np.array([[0, 1],
              [1, -1]])

# Ánh xạ
F_moi = A @ F
print("Tọa độ sau biến đổi:\n", F_moi)


Tọa độ sau biến đổi:
 [[ 0  1  1  0]
 [ 0 -1  0  1]]


In [16]:
#Bài 3
v1, v2 = sp.symbols('v1 v2')
T = sp.Matrix([v1 - v2, v1 + 2*v2])

# Kiểm tra tuyến tính: T(a*u + b*v) == a*T(u) + b*T(v)
a, b = sp.symbols('a b')
u1, u2 = sp.symbols('u1 u2')
w1, w2 = sp.symbols('w1 w2')

# Tính T(a*u + b*v)
T_comb = sp.Matrix([
    (a*u1 + b*w1) - (a*u2 + b*w2),
    (a*u1 + b*w1) + 2*(a*u2 + b*w2)
])

# Tính a*T(u) + b*T(w)
Tu = sp.Matrix([u1 - u2, u1 + 2*u2])
Tv = sp.Matrix([w1 - w2, w1 + 2*w2])
T_linear = a*Tu + b*Tv

print("Ánh xạ tuyến tính?", sp.simplify(T_comb - T_linear) == sp.Matrix([0, 0]))


Ánh xạ tuyến tính? True


In [17]:
#Bài 4
A = sp.Matrix([[13, -5], [-5, 13]])

# Trị riêng
eigenvals = A.eigenvals()
eigenvects = A.eigenvects()

print("Trị riêng:", eigenvals)

# Tính góc quay
theta = sp.atan2(5, 13)
print("Góc quay (rad):", theta)
print("Góc quay (deg):", sp.N(theta * 180 / sp.pi))


Trị riêng: {18: 1, 8: 1}
Góc quay (rad): atan(5/13)
Góc quay (deg): 21.0375110254218
